apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mac-k8s-config
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/pc-dae-gitops/mac-k8s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-components
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./local-cluster/gotk
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/pc-dae-gitops/local-k8s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ././local-cluster/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

